@startuml push_overview
!theme gematik from ../puml

skinparam ranksep 10

cloud "e.g. Apple/Google" {
    component "Push Provider" as PushProvider
}

cloud "TI" {
    component Fachdienst

    package "App Developer" {
        component "Push Gateway" as PushGateway
        component "FdV\n(Mobile Device)" as MobileDevice
    }
}

PushGateway -left-> PushProvider
MobileDevice <-left.> PushProvider

PushGateway -[hidden]- MobileDevice

Fachdienst <-left- MobileDevice : "Register"
PushGateway <-right- Fachdienst: "Send Push"

@enduml
