@startuml push_history
!theme gematik from ../puml

actor "FdV" as App
entity "Fachdienst\n" as Fachdienst
entity "Push Gateway\n" as NotificationService
entity "Notification Provider\n(e.g. Apple/Google)" as NotificationProvider

entity "Internal\nServices" as PrivateNotificationService

group SendPush
    Fachdienst -> Fachdienst : event_trigger
    activate Fachdienst
    Fachdienst -> Fachdienst : encrypt_message
    Fachdienst -> NotificationService : **POST** //push/v1/notify//
    activate NotificationService
    NotificationService -->> Fachdienst : status
    deactivate Fachdienst

    NotificationService -> PrivateNotificationService : get_push_token(for: pushkey)
    activate PrivateNotificationService
    PrivateNotificationService -> NotificationService : push_token
    deactivate PrivateNotificationService

    NotificationService -> NotificationProvider : send_push
    activate NotificationProvider


    NotificationProvider -> App : push
    deactivate NotificationProvider
    activate App

    NotificationService -> PrivateNotificationService : register(\n\tpush: {service:epa, date:now()},\n\tfor: pushkey\n)    
    activate PrivateNotificationService
    PrivateNotificationService -> NotificationService
    deactivate PrivateNotificationService

    deactivate NotificationService

    App -> App : decrypt_notification
    App -> App : show_notification
end

deactivate App

@enduml
