@startuml registration_complex
!theme gematik from ../puml

actor "FdV" as App
entity "Fachdienst\n" as Fachdienst
entity "Push Gateway\n" as NotificationService
entity "Notification Provider\n(e.g. Apple/Google)" as NotificationProvider

entity "Internal\nServices" as PrivateNotificationService

group Registration
    activate App
    App -> NotificationProvider : get_device_push_token
    activate NotificationProvider
    NotificationProvider -->> App : device_push_token
    deactivate NotificationProvider

    App -> PrivateNotificationService : get_pushkey(device_push_token)
    activate PrivateNotificationService
    PrivateNotificationService -->> App : pushkey
    deactivate PrivateNotificationService

    App -> App : create iss
    App -> Fachdienst : **POST** //pushers/v1/set//
    activate Fachdienst
    Fachdienst -> Fachdienst : store information
    Fachdienst -->> App : status
    deactivate Fachdienst
end

group SendPush
    Fachdienst -> Fachdienst : event_trigger
    activate Fachdienst
    Fachdienst -> Fachdienst : encrypt_message
    Fachdienst -> NotificationService : **POST** //push/v1/notifyEncrypted/batch//
    activate NotificationService
    NotificationService -->> Fachdienst : status
    deactivate Fachdienst

    NotificationService -> PrivateNotificationService : get_push_token(for: pushkey)
    activate PrivateNotificationService
    PrivateNotificationService -> NotificationService : push_token
    deactivate PrivateNotificationService
    NotificationService -> NotificationProvider : send_push
    deactivate NotificationService

    activate NotificationProvider
    NotificationProvider -> App : push
    deactivate NotificationProvider

    activate App
    App -> App : decrypt_notification
    App -> App : show_notification
end

deactivate App

@enduml
